### ISSUE TITLE
DTraceProviderBindings errors on FreeBSD

### ISSUE THREAD

**Issue by webvoyant** [joyent/node-triton#187]
These errors show up on FreeBSD 10 and 11. To replicate, I provisioned FreeBSD KVM instances in Triton public cloud and installed this tool with `npm install -g triton`. Then, upon executing `triton`, the errors are displayed.

**FreeBSD 10:**
```
root@freebsd10:~ # uname -a
FreeBSD freebsd10 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25 02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
root@freebsd10:~ # node -v
v5.9.1
root@freebsd10:~ # npm list -g triton
/usr/local/lib
└── triton@5.1.0

root@freebsd10:~ # triton
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
Joyent Triton CLI and client (https://www.joyent.com/triton)

Usage:
    triton [OPTIONS] COMMAND [ARGS...]
    triton help COMMAND

Options:
    -h, --help                          Print this help and exit.
    --version                           Print version and exit.
    -v, --verbose                       Verbose/debug output.
    -p NAME, --profile=NAME             Triton client profile to use.
                                        Environment: TRITON_PROFILE=NAME

  CloudAPI Options:
    -a ACCOUNT, --account=ACCOUNT       Account (login name). Environment:
                                        TRITON_ACCOUNT=ACCOUNT or
                                        SDC_ACCOUNT=ACCOUNT.
    -u USER, --user=USER                RBAC user (login name). Environment:
                                        TRITON_USER=USER or SDC_USER=USER.
    -r ROLE,ROLE,..., --role=ROLE,ROLE,...
                                        Assume an RBAC role. Use multiple times
                                        or once with a list. Environment:
                                        MANTA_ROLE=ROLE,ROLE,...
    -k FP, --keyId=FP                   SSH key fingerprint. Environment:
                                        TRITON_KEY_ID=FINGERPRINT or
                                        SDC_KEY_ID=FINGERPRINT.
    -U URL, --url=URL                   CloudAPI URL. Environment:
                                        TRITON_URL=URL or SDC_URL=URL.
    -i, --insecure                      Do not validate the CloudAPI SSL
                                        certificate. Environment:
                                        TRITON_TLS_INSECURE=1,
                                        SDC_TLS_INSECURE=1 (or the deprecated
                                        SDC_TESTING=1).

Commands:
    help (?)                  Help on a specific sub-command.
    profile                   List, get, create and update Triton CLI profiles.
    env                       Emit shell commands to setup environment.
    completion                Emit bash completion. See help for installation.

  Instances (aka VMs/Machines/Containers):
    instance (inst)           List and manage Triton instances.
    instances (insts, ls)     A shortcut for "triton instance list".
    create                    A shortcut for "triton instance create".
    delete (rm)               A shortcut for "triton instance delete".
    start                     A shortcut for "triton instance start".
    stop                      A shortcut for "triton instance stop".
    reboot                    A shortcut for "triton instance reboot".
    ssh                       A shortcut for "triton instance ssh".
    ip                        A shortcut for "triton instance ip".

  Images, Packages, Networks, Firewall Rules:
    image (img)               List and manage Triton images.
    package (pkg)             List and get Triton packages.
    network                   List and manage Triton networks.
    fwrule                    List and manage Triton firewall rules.

  Other Commands:
    info                      Print an account summary.
    account                   Get and update your Triton account.
    key                       Account SSH key commands.
    services                  Show services information
    datacenters               Show datacenters in this cloud.

Exit Status:
    0   Successful completion.
    1   An error occurred.
    2   Usage error.
    3   "ResourceNotFound" error (when an instance, image, etc. with
        the given name or id is not found) or "InstanceDeleted" error.
```

**FreeBSD 11**
```
root@freebsd11:~ # uname -a
FreeBSD freebsd11 11.0-RELEASE-p2 FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
root@freebsd11:~ # node -v
v6.9.1
root@freebsd11:~ # npm list -g triton
/usr/local/lib
`-- triton@5.1.0

root@freebsd11:~ # triton
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
Joyent Triton CLI and client (https://www.joyent.com/triton)

Usage:
    triton [OPTIONS] COMMAND [ARGS...]
    triton help COMMAND

Options:
    -h, --help                          Print this help and exit.
    --version                           Print version and exit.
    -v, --verbose                       Verbose/debug output.
    -p NAME, --profile=NAME             Triton client profile to use.
                                        Environment: TRITON_PROFILE=NAME

  CloudAPI Options:
    -a ACCOUNT, --account=ACCOUNT       Account (login name). Environment:
                                        TRITON_ACCOUNT=ACCOUNT or
                                        SDC_ACCOUNT=ACCOUNT.
    -u USER, --user=USER                RBAC user (login name). Environment:
                                        TRITON_USER=USER or SDC_USER=USER.
    -r ROLE,ROLE,..., --role=ROLE,ROLE,...
                                        Assume an RBAC role. Use multiple times
                                        or once with a list. Environment:
                                        MANTA_ROLE=ROLE,ROLE,...
    -k FP, --keyId=FP                   SSH key fingerprint. Environment:
                                        TRITON_KEY_ID=FINGERPRINT or
                                        SDC_KEY_ID=FINGERPRINT.
    -U URL, --url=URL                   CloudAPI URL. Environment:
                                        TRITON_URL=URL or SDC_URL=URL.
    -i, --insecure                      Do not validate the CloudAPI SSL
                                        certificate. Environment:
                                        TRITON_TLS_INSECURE=1,
                                        SDC_TLS_INSECURE=1 (or the deprecated
                                        SDC_TESTING=1).

Commands:
    help (?)                  Help on a specific sub-command.
    profile                   List, get, create and update Triton CLI profiles.
    env                       Emit shell commands to setup environment.
    completion                Emit bash completion. See help for installation.

  Instances (aka VMs/Machines/Containers):
    instance (inst)           List and manage Triton instances.
    instances (insts, ls)     A shortcut for "triton instance list".
    create                    A shortcut for "triton instance create".
    delete (rm)               A shortcut for "triton instance delete".
    start                     A shortcut for "triton instance start".
    stop                      A shortcut for "triton instance stop".
    reboot                    A shortcut for "triton instance reboot".
    ssh                       A shortcut for "triton instance ssh".
    ip                        A shortcut for "triton instance ip".

  Images, Packages, Networks, Firewall Rules:
    image (img)               List and manage Triton images.
    package (pkg)             List and get Triton packages.
    network                   List and manage Triton networks.
    fwrule                    List and manage Triton firewall rules.

  Other Commands:
    info                      Print an account summary.
    account                   Get and update your Triton account.
    key                       Account SSH key commands.
    services                  Show services information
    datacenters               Show datacenters in this cloud.

Exit Status:
    0   Successful completion.
    1   An error occurred.
    2   Usage error.
    3   "ResourceNotFound" error (when an instance, image, etc. with
        the given name or id is not found) or "InstanceDeleted" error.
```

**Comment by melloc** [comment]
@webvoyant I just merged chrisa/node-dtrace-provider#94 and published version 0.8.1, which adds FreeBSD support. If you have `/usr/src` installed locally and reinstall, you should be able to pick up and compile the latest version, which should fix this issue for you.

**Comment by webvoyant** [comment]
@melloc Thanks, version 0.8.1 was installed, but unfortunately, the errors still remain. Here are the steps I took for each install:

**FreeBSD 10**
```
root@freebsd10:~ # pkg install ca_root_nss subversion gcc
...
root@freebsd10:~ # svn checkout https://svn.FreeBSD.org/base/stable/10 /usr/src
...
root@freebsd10:~ # npm install -g triton
...
root@freebsd10:~ # npm list -g dtrace-provider
/usr/local/lib
└─┬ triton@5.1.0
  ├─┬ bunyan@1.5.1
  │ └── dtrace-provider@0.6.0
  ├─┬ restify-clients@1.5.0
  │ ├─┬ bunyan@1.8.8
  │ │ └── dtrace-provider@0.8.1
  │ └── dtrace-provider@0.7.1
  └─┬ sshpk-agent@1.4.2
    └─┬ mooremachine@2.1.0
      └── dtrace-provider@0.8.1

root@freebsd10:~ # triton
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
Joyent Triton CLI and client (https://www.joyent.com/triton)

Usage:
    triton [OPTIONS] COMMAND [ARGS...]
    triton help COMMAND

Options:
...
```

**FreeBSD 11**
```
root@freebsd11:~ # pkg install ca_root_nss subversion gcc
...
root@freebsd11:~ # svn checkout https://svn.FreeBSD.org/base/stable/11 /usr/src
...
root@freebsd11:~ # npm install -g triton
...
root@freebsd11:~ # npm list -g dtrace-provider
/usr/local/lib
`-- triton@5.1.0
  +-- bunyan@1.5.1
  | `-- dtrace-provider@0.6.0
  +-- restify-clients@1.5.0
  | +-- bunyan@1.8.8
  | | `-- dtrace-provider@0.8.1
  | `-- dtrace-provider@0.7.1
  `-- sshpk-agent@1.4.2
    `-- mooremachine@2.1.0
      `-- dtrace-provider@0.8.1

root@freebsd11:~ # triton
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/triton/node_modules/restify-clients/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
Joyent Triton CLI and client (https://www.joyent.com/triton)

Usage:
    triton [OPTIONS] COMMAND [ARGS...]
    triton help COMMAND

Options:
...
```

**Comment by melloc** [comment]
Ah, sorry. It looks like `node-triton` depends on `bunyan@1.5.1`. The dependency will need to be updated to one of the 1.8.x releases to pull in `dtrace-provider@0.8.1`. I'll make a CR for updating it.

**Comment by metsuke0** [comment]
I also have this issue on FreeBSD and it prohibits real usage since it throws an error when a command is given: `triton inst list`

The workaround is to comment out the line in /usr/local/lib/node_modules/triton/node_modules/mooremachine/lib/fsm.js that reads `dt.provider.enable();`

**Comment by bahamat** [comment]
Filed internally as [TOOLS-1863](https://smartos.org/bugview/TOOLS-1863).

**Comment by trentm** [comment]
Published triton@5.3.2 that should fix this. Please re-open if that isn't the case. Thanks!
